spring.application.name=smart-inventory-system

# Active Profile (change to staging or live when needed)
spring.profiles.active=development

# Common settings
server.port=8080
server.servlet.context-path=/

# Logging
logging.level.org.springframework=INFO
logging.level.com.smart.inventory.system=DEBUG