# ====================== STAGING PROFILE ======================
spring.datasource.url=jdbc:mysql://staging-host:3306/smart_inventory_db
spring.datasource.username=staging_user
spring.datasource.password=staging_pass

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true